### ISSUE TITLE
UI Issue: Text Color Change in 'Amount' Input Field on Peanut's Site Send "Path"

### ISSUE THREAD

**Issue by yhoungdev** [peanutprotocol/peanut-ui#98]
I Noticed a UI issue on this path of the peanut site https://peanut.to/send

Input Field text color becomes white when typing the Amount i want. 

This is how it is by default 
![Screenshot from 2023-12-07 06-21-43](https://github.com/peanutprotocol/peanut-ui/assets/54102389/a5fdda0e-d230-4b37-88eb-1d198fa27edb)

And it turns to white text color, which is not visible due to background of the text field 

![Screenshot from 2023-12-07 06-44-45](https://github.com/peanutprotocol/peanut-ui/assets/54102389/e5dbd54a-729b-46ab-83d8-c1a8b5d708b3)

**Comment by borcherd** [comment]
Thanks for noticing! fixed!

**Comment by theobiabo** [comment]
Awesome

**Comment by theobiabo** [comment]
tested again, same issue, maybe you havnt deploy to prod
